### PR TITLE
No one can use our scripts until we change this :)

### PR DESCRIPTION
**Pull request by TheBlocks**
Is this okay?

### CODE REVIEW

**Comment by MobFactory** [comment]
Unfortunately we cant. Well. The EUPL licence i used is litterally the most locked down open source license out there. If you want to set it up as closed source its cool though and in that case yeah its fine. I might ammend 1 or 2 things for legal reasons.

That being said idk if your allowed to have a all rights reserved (closed source) project on github

**Comment by MobFactory** [comment]
should be fine though

**Comment by MobFactory** [comment]
Is still dont think this feels right. The whole point of github is open source.

**Comment by TheBlocks** [comment]
Use EUPL then

**Comment by TheBlocks** [comment]
I'm fine with anyone using our code, but not during the competition. That would be unfair to us.

**Comment by MobFactory** [comment]
ok I'll merge now. After the competition we will put it back to EUPL

**Pull request merged**
